version: 2
jobs:
  test-and-build:
    environment:
      - JVM_OPTS: "-Xms512m -Xmx1024m"
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run:
          name: Build and Install
          command: lein install
      - run:
          name: Run tests
          command: lein test
      - save-cache:
          paths:
          - ~/.m2
          - ~/.lein
          key: lein-git-deps-{{ checksum "project.clj" }}
      - persist_to_workspace:
          root: .
          paths:
          - target

workflows:
  version: 2
  deploy:
    jobs:
      - test-and-build
